# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/cards.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCards(HttpRunner):

    config = Config("获取赛事卡片").base_url("${ENV(BASE_URL)}").verify(False)

    teststeps = [
        Step(
            RunRequest("获取赛事卡片")
            .get(
                "/3/7.5.26/bplapi/device/v1/home/cards"
            )
            .with_params(
                **{
                    "cid": "88505902",
                }
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", 200)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseCards().test_start()
