# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/perinformation/changeheader.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword
import pytest
from httprunner import Parameters

class TestCaseChangeheader(HttpRunner):
    @classmethod
    def setup_class(cls):
        print("运行于测试用例之前")

    @classmethod
    def teardown_class(cls):
        print("运行于测试用例之后")

    @pytest.mark.parametrize("param", Parameters(
        {"title-headerPath-status-msg": "${get_headerinfo()}"}
    ), )
    def test_start(self, param):
        super().test_start(param)

    config = Config("testcase description").base_url("${ENV(BASE_URL_PRE)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("改头像")
            .post(
                "/3/7.5.28/bplapi/user/v2/uploadHeader"
            )
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.28 iPhone11,6",
                }
            )
            .with_data(
                {
                    "headerPath": "$headerPath",
                    "nickname": "$nickname",
                }
            )
            .validate()
            .assert_equal("body.status", "$status")
            .assert_equal("body.msg", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseChangeheader().test_start()
