# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/perinformation/getCityList.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword


class TestCaseGetcitylist(HttpRunner):

    config = Config("testcase description").base_url("${ENV(BASE_URL_PRE)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("获取城市列表")
            .get(
                "/3/7.5.28/bplapi/user/v1/getCityList"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.28 iPhone11,6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetcitylist().test_start()
