# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/sendmsg.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword

class TestCaseSendmsg(HttpRunner):

    config = Config("testcase description").base_url("${ENV(BASE_URL)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("/3/7.5.26/bplapi/inmail/front/pm/v1/sendPm")
            .post(
                "/3/7.5.26/bplapi/inmail/front/pm/v1/sendPm"
            )
            .with_params(**{"client": "3102879F-6EE8-41D4-BCD0-4A95BCE06D06"})
            .with_headers(
                **{
                    "Content-Type": "application/json; encoding=utf-8",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",
                }
            )
            .with_json(
                {
                    "sendPuid": "46864351",
                    "bddid": "1494963246608280",
                    "clientId": "88505902",
                    "sign": "2ee31864ef8d6b87e891fd39a50c3bc8",
                    "advId": "2D6A0DB0-A6E8-48FF-B1A0-135C510E930E",
                    "reveiverPuid": "52498468",
                    "allowLink": 0,
                    "token": "MzY3NTA4ODk=|MTYwOTE0ODQ3Nw==|b23c1a95fa1156e3aef9cc77add062f7",
                    "night": "0",
                    "crt": "1609148477",
                    "time_zone": "Asia\/Shanghai",
                    "client": "3102879F-6EE8-41D4-BCD0-4A95BCE06D06",
                    "content": "哈哈"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", 200)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseSendmsg().test_start()
