# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/clloectList.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword

class TestCaseClloectlist(HttpRunner):
    config = Config("testcase description").base_url("${ENV(BASE_URL_PRE)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("/3/7.5.26/collect/getThreadsCollectList")
            .get(
                "/3/7.5.26/collect/getThreadsCollectList"
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.is_login", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseClloectlist().test_start()
