# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/demo_testcase_request.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from .login_test import TestCaseTest

class TestCaseDemoTestcaseRequest(HttpRunner):

    config = (
        Config("request methods testcase with functions")
        .base_url("https://games.mobileapi.hupu.com")
        .verify(False)
        .export(*["cookietoken"])
    )

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseTest)

        ),
        Step(
            RunRequest("查看收藏列表")
            .get("/1/7.5.26/collect/getThreadsCollectList")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "text/plain",
                    # "cookies"="get_cookies()"

                }
            )
            .with_cookies(
                **{
                    "pctpct": "oocbtBskUKNrDpDgVzl919lITzvQqo2inbluXdLCFlUJVB7%2B9j6xq57IS%2FYKWrpMnhcci8bQ2FILSMpEvfaIsA%3D%3D",
                    "cid": "88505902",
                    "cpck": "eyJpZGZhIjoiMkQ2QTBEQjAtQTZFOC00OEZGLUIxQTAtMTM1QzUxMEU5MzBFIiwiY2xpZW50IjoiMzEwMjg3OUYtNkVFOC00MUQ0LUJDRDAtNEE5NUJDRTA2RDA2IiwicHJvamVjdElkIjozfQ%3D%3D",
                    "sensorsdata2015jssdkcross": "%7B%22distinct_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22%24device_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D",
                    "__dacevid3":"0xb330c188a1152449"

                }
            )
            .with_params(
                **{"clientId": 90062738,"sign": "ced59608fb8da0cc83b2b50035d31188",
                            "client": "8f74bfbade53cc1a", "page": 1}
            )
            .extract().with_jmespath("result","result")
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal("status", 1)


        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcaseRequest().test_start()
