# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/test.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTest(HttpRunner):

    config = Config("账号密码登录").base_url("https://games.mobileapi.hupu.com").verify(False)

    teststeps = [
        Step(
            RunRequest("账号密码登录")
            .post("/1/7.5.26/bplapi/user/v1/loginByEmailPassword?client=6d61684741a1408c")
            .with_headers(
                **{
                    "User-Agent": " Mozilla/5.0 (Linux; Android 10; HRY-AL00a Build/HONORHRY-AL00a; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36 kanqiu/7.5.26.12725/7748 isp/1 network/13",
                    "Content-Type": "application/x-www-form-urlencoded"
                }
            )
            .with_data(
                "username =13817441237&password =65618383e140db353d238a14a1fdb2f5&timeline=1608111672&client=6d61684741a1408c"
            )
            # .extract().with_jmespath("cookies", "cookietoken")
            # print("cookietoken")
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal("isLogin", 1)


        ),
    ]


if __name__ == "__main__":
    TestCaseTest().test_start()
