# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/homepage/homepage.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword


class TestCaseHomepage(HttpRunner):

    config = Config("testcase description").base_url("${ENV(BASE_URL_PRE)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("个人主页")
            .post("/3/7.5.28/bplapi/user/v1/page")
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.28 iPhone11,6",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )

            .with_data({})
            .validate()
            .assert_equal("body.status", 200)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseHomepage().test_start()
