# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/ homepage/user_more.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUserMore(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/3/7.5.26/bplapi/user/v1/more")
            .get("https://games.mobileapi.hupu.com/3/7.5.26/bplapi/user/v1/more")
            .with_params(
                **{
                    "time_zone": "Asia/Shanghai",
                    "client": "3102879F-6EE8-41D4-BCD0-4A95BCE06D06",
                    "advId": "2D6A0DB0-A6E8-48FF-B1A0-135C510E930E",
                    "night": "0",
                    "crt": "1609156685",
                    "userMoreLibra": '{"usermorejrsui":"1"}',
                    "clientId": "88505902",
                    "bddid": "1494963246608280",
                    "sign": "cfba3571a034a2f27940085415104b4c",
                }
            )
            .with_headers(
                **{
                    "Host": "games.mobileapi.hupu.com",
                    "Cookie": "cpck=eyJpZGZhIjoiMkQ2QTBEQjAtQTZFOC00OEZGLUIxQTAtMTM1QzUxMEU5MzBFIiwiY2xpZW50IjoiMzEwMjg3OUYtNkVFOC00MUQ0LUJDRDAtNEE5NUJDRTA2RDA2IiwicHJvamVjdElkIjozfQ%3D%3D; pctpct=2i4LouBo9%2FD58ml28UU%2BYLHHV1fLUPE%2BD5zaw4lm8dzpvNplVeKnSxg7v1C8vV8vu7z6R%2F4SY1uDFpGCtxc%2Bag%3D%3D; cid=88505902; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22%24device_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D; __dacevid3=0xb330c188a1152449",
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",
                    "Connection": "keep-alive",
                    "Accept-Encoding": "gzip",
                }
            )
            .with_cookies(
                **{
                    "cpck": "eyJpZGZhIjoiMkQ2QTBEQjAtQTZFOC00OEZGLUIxQTAtMTM1QzUxMEU5MzBFIiwiY2xpZW50IjoiMzEwMjg3OUYtNkVFOC00MUQ0LUJDRDAtNEE5NUJDRTA2RDA2IiwicHJvamVjdElkIjozfQ%3D%3D",
                    "pctpct": "2i4LouBo9%2FD58ml28UU%2BYLHHV1fLUPE%2BD5zaw4lm8dzpvNplVeKnSxg7v1C8vV8vu7z6R%2F4SY1uDFpGCtxc%2Bag%3D%3D",
                    "cid": "88505902",
                    "sensorsdata2015jssdkcross": "%7B%22distinct_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22%24device_id%22%3A%2217617009d0a22d-0f9103e285b9d8-6703485b-304500-17617009d0bd33%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D",
                    "__dacevid3": "0xb330c188a1152449",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.status", 200)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseUserMore().test_start()
