# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/login/loginByEmailPassword.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginbyemailpassword(HttpRunner):

    config = Config("testcase description")\
        .base_url("${ENV(BASE_URL_PRE)}").verify(False).export(*["nickname"])

    teststeps = [
        Step(
            RunRequest("/3/7.5.26/bplapi/user/v1/loginByEmailPassword")
            .post(
                "/3/7.5.26/bplapi/user/v1/loginByEmailPassword"
            )
            .with_params(**{"client": "3102879F-6EE8-41D4-BCD0-4A95BCE06D06"})
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",
                }
            )

            .with_data(
                {

                    "password": "65618383e140db353d238a14a1fdb2f5",
                    "username": "13817441237",

                }
            )
            .extract()
            .with_jmespath("body.result.nickname", "nickname")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.isLogin", 1)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginbyemailpassword().test_start()
