# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/getTimeline.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from hrun_demo.loginByEmailPassword_test import TestCaseLoginbyemailpassword
from httprunner import Parameters
import pytest

class TestCaseGettimeline(HttpRunner):
    @classmethod
    def setup_class(cls):
        print("运行于测试用例之前")

    @classmethod
    def teardown_class(cls):
        print("运行于测试用例之后")

    @pytest.mark.parametrize("param", Parameters(
        {"title-page-puid-type-lastCommentTime-status-msg": "${get_timeline()}"}
    ), )
    def test_start(self, param):
        super().test_start(param)

    config = Config("获取动态列表").base_url("${ENV(BASE_URL)}").verify(False)

    teststeps = [
        Step(
            RunTestCase("登录")
            .call(TestCaseLoginbyemailpassword)

        ),
        Step(
            RunRequest("$title")
            .get(
                "/3/7.5.26/bplapi/timeline/v1/getTimeline"
            )
            .with_params(
                **{
                    "page": "$page",
                    "type": "$type",
                    "puid": "$puid",
                    "lastCommentTime": "$lastCommentTime",

                }
            )
            .with_headers(
                **{
                    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 isp/unknown network/WIFI prokanqiu/7.5.26 iPhone13,2",

                }
            )

            .validate()
            .assert_equal("body.status", "$status")
            .assert_equal("body.msg", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseGettimeline().test_start()
